name: pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  compiler:
    runs-on: &ubuntu ubuntu-latest

    defaults:
      run:
        working-directory: compiler

    steps:
      - uses: &checkout actions/checkout@v5
      - uses: &rust dtolnay/rust-toolchain@stable
      - uses: &cache Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Install CLI Tools
        run: cargo install cargo-shear cargo-bloat

      - name: Unused code
        run: |
          cargo shear
          cargo clippy

      - name: Binary Size
        run: |
          echo "Libraries and binaries"
          cargo bloat --release --creates
          echo "Bigger Features"
          cargo bloat --release -n 20

  deployment:
    runs-on: *ubuntu

    defaults:
      run:
        working-directory: deployment
      
    steps:
      - uses: *checkout
      - uses: *rust
      - uses: *cache

      - name: Build
        run: cargo build
      
      - name: Run tests
        run: cargo test

      - name: Install cargo-shear
        run: cargo install cargo-shear

      - name: Unused code
        run: |
          cargo shear
          cargo clippy