on:
  workflow_call:

jobs:
  build:
    name: WebAssembly
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: compiler

    steps:
      - uses: actions/checkout@v5

      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install target
        run: rustup target add wasm32-unknown-unknown

      - name: Install CLI Tools
        run: |
          cargo install cargo-shear
          sudo apt update
          sudo apt-get install -y binaryen

      - name: Build
        run: cargo build --target wasm32-unknown-unknown --features wasm --lib --release

      - name: Unused Code
        run: cargo shear && cargo clippy --lib --target wasm32-unknown-unknown --features wasm

      - name: Size
        run: ls -lh target/wasm32-unknown-unknown/release/compiler_lib.wasm

      - name: Optimize
        run: |
          wasm-opt -Oz --converge --strip-debug \
            --enable-bulk-memory \
            --enable-nontrapping-float-to-int \
            --enable-sign-ext \
            -o target/wasm32-unknown-unknown/release/compiler_lib.wasm \
            target/wasm32-unknown-unknown/release/compiler_lib.wasm

      - name: Size (optimized)
        run: ls -lh target/wasm32-unknown-unknown/release/compiler_lib.wasm

      - name: Test
        run: cargo test --features wasm-tests
      
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: compiler/target/wasm32-unknown-unknown/release/compiler_lib.wasm